apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      format json
      path /var/log/app.log
      pos_file /var/log/app.log.pos
      tag bigquery
    </source>

    <match bigquery>
      @type bigquery

      method load

      <buffer time>
        @type file
        path /var/log/bigquery.*.buffer
        timekey 1d
        flush_at_shutdown true
      </buffer>

      auth_method	compute_engine

      project k8s-sandbox-pj
      dataset sample_dataset
      table sample_table$%Y%m%d
      fetch_schema true
      ignore_unknown_values true
    </match>
